run:
  timeout: 5m
  tests: true

linters:
  enable:
    - revive
    - gofmt
    - staticcheck
    - govet
    - misspell
    - ineffassign
    - errcheck
    - unused
  enable-all: false

linters-settings:
  govet:
    settings:
      shadow:
        strict: true
    enable-all: true
