[[constraint]]
  name = "github.com/Shopify/sarama"
  revision = "e7238b119b7daab993720f0153eafb88e2b0ac1f"

[[constraint]]
  name = "github.com/linkedin/goavro"
  version = "~2.3.0"

[[constraint]]
  name = "github.com/newrelic/go-agent"
  version = "~2.0.0"

[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "~1.0.2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "~1.2.1"

[[constraint]]
  name = "github.com/uber/jaeger-client-go"
  version = "~2.14.0"

[[constraint]]
  name = "go.uber.org/zap"
  version = "~1.9.1"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "~0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "~1.0.2"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "~1.0.1"

[[constraint]]
  name = "github.com/getsentry/raven-go"
  revision = "ed7bcb39ff10f39ab08e317ce16df282845852fa"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  revision = "5b23715facdef1452016bae512489c3cdf82458c"

[[constraint]]
  name = "github.com/rcrowley/go-metrics"
  revision = "e2704e165165ec55d062f5919b4b29494e9fa790"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.0"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "8.0.0"

[prune]
  go-tests = true
  unused-packages = true
