[[constraint]]
  branch = "master"
  name = "github.com/spothero/core"

[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "1.0.2"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.9.1"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.0"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "8.0.0"

[prune]
  go-tests = true
  unused-packages = true
